In [1]:
import pandas as pd
import numpy as np

In [2]:
#Importing database
data = pd.read_csv('data/sample.csv')

In [3]:
data.head()

,producto,presentacion,marca,categoria,catalogo,precio,fechaRegistro,cadenaComercial,giro,nombreComercial,direccion,estado,municipio,latitud,longitud
0,CUADERNO FORMA ITALIANA,96 HOJAS PASTA DURA. CUADRICULA CHICA,ESTRELLA,MATERIAL ESCOLAR,UTILES ESCOLARES,25.9,2011-05-18 00:00:00.000,ABASTECEDORA LUMEN,PAPELERIAS,ABASTECEDORA LUMEN SUCURSAL VILLA COAPA,CANNES No. 6 ESQ. CANAL DE MIRAMONTES,DISTRITO FEDERAL,TLALPAN,19.29699,-99.125417
1,CRAYONES,CAJA 12 CERAS. JUMBO. C.B. 201423,CRAYOLA,MATERIAL ESCOLAR,UTILES ESCOLARES,27.5,2011-05-18 00:00:00.000,ABASTECEDORA LUMEN,PAPELERIAS,ABASTECEDORA LUMEN SUCURSAL VILLA COAPA,CANNES No. 6 ESQ. CANAL DE MIRAMONTES,DISTRITO FEDERAL,TLALPAN,19.29699,-99.125417
2,CRAYONES,CAJA 12 CERAS. TAMANO REGULAR C.B. 201034,CRAYOLA,MATERIAL ESCOLAR,UTILES ESCOLARES,13.9,2011-05-18 00:00:00.000,ABASTECEDORA LUMEN,PAPELERIAS,ABASTECEDORA LUMEN SUCURSAL VILLA COAPA,CANNES No. 6 ESQ. CANAL DE MIRAMONTES,DISTRITO FEDERAL,TLALPAN,19.29699,-99.125417
3,COLORES DE MADERA,CAJA 12 PIEZAS LARGO. TRIANGULAR. C.B. 640646,PINCELIN,MATERIAL ESCOLAR,UTILES ESCOLARES,46.9,2011-05-18 00:00:00.000,ABASTECEDORA LUMEN,PAPELERIAS,ABASTECEDORA LUMEN SUCURSAL VILLA COAPA,CANNES No. 6 ESQ. CANAL DE MIRAMONTES,DISTRITO FEDERAL,TLALPAN,19.29699,-99.125417
4,COLOR LARGO,CAJA 36 PIEZAS. CON SACAPUNTAS. 68-4036,CRAYOLA,MATERIAL ESCOLAR,UTILES ESCOLARES,115.0,2011-05-18 00:00:00.000,ABASTECEDORA LUMEN,PAPELERIAS,ABASTECEDORA LUMEN SUCURSAL VILLA COAPA,CANNES No. 6 ESQ. CANAL DE MIRAMONTES,DISTRITO FEDERAL,TLALPAN,19.29699,-99.125417

In [7]:
def count_chains(series):
    """This function iterates through the chains column, verifies if the name is inside a
    list that we will create as we move through the column, add the name to the list if it isn't already in it
    and add 1 to the counter"""
    #Defining non local variable outside of the scope of this function to make this a nonpure function.
    global count
    chains = []
    for i in series:
        if i in chains:
            pass
        else:
            chains.append(i)
            count += 1
        
    return count

In [8]:
#Declaring variable outside of the count_chains function.
count = 0
# Using function to count 'cadenaComercial' column.
count = count_chains(data['cadenaComercial'])
print(count)

4

In [12]:
#Function that retrun the length of a pandas series
def len_series(series):
    length = 0
    for i in series:
        length += 1
    
    return length

In [13]:
cuenta = 0
for i in range_series(data['cadenaComercial']):
    cuenta += 1

cuenta

2

In [ ]:
def top_10(series):
    states = dict()
    for i in range(len_series(series)):

In [25]:
top_products = data.groupby(['estado','producto']).agg({'producto':'count'})
top_products.head(10)

                                                 producto
estado           producto
DISTRITO FEDERAL ACEITE                                11
                 ACEITE DE OLIVA                        6
                 ACEITUNA                               3
                 ACEITUNA. GORDAL                       1
                 ACEITUNA. RELLENA CON PIMIENTO         1
                 ACELGA                                 1
                 ACONDICIONADOR / ENJUAGUE              6
                 ACONDICIONADOR Y ENJUAGUE              4
                 AGUA CON GAS                           4
                 AGUA SIN GAS                           7